-- AlterTable
ALTER TABLE "users" ADD COLUMN "elo_rating" INTEGER NOT NULL DEFAULT 1200,
ADD COLUMN "duels_played" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Quiz" ADD COLUMN "isPublic" BOOLEAN NOT NULL DEFAULT false;
